before_install:
  - psql --version
  - sudo service postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-get update -qq
  - sudo apt-get -y install bc libpam-dev libedit-dev
  - git clone https://github.com/postgres/postgres.git postgres-dev
  - cd postgres-dev
  - export POSTGRES_HOME=/home/travis/build/ossc-db/pg_rman/pgsql/$PGVERSION
  - echo 'export POSTGRES_HOME=/home/travis/build/ossc-db/pg_rman/pgsql/$PGVERSION' >> ~/.bashrc
  - ./configure --prefix=$POSTGRES_HOME
  - make -j 2
  - make install
  - echo 'export PATH=$PATH:$POSTGRES_HOME/bin' >> ~/.bashrc
  - export PATH=$PATH:$POSTGRES_HOME/bin
  - echo 'export PGDATA=/home/travis/build/ossc-db/pg_rman/pg_data/$PGVERSION' >> ~/.bashrc
  - export PGDATA=/home/travis/build/ossc-db/pg_rman/pg_data/$PGVERSION
  - mkdir -p $PGDATA
  - mkdir -p /home/travis/build/ossc-db/pg_rman/pg_data/archivelog
  - initdb --no-locale -D $PGDATA
  - sudo echo "local   all         postgres                          trust" > $PGDATA/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> $PGDATA/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> $PGDATA/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> $PGDATA/pg_hba.conf
  - sudo echo "logging_collector = on" >> $PGDATA/postgresql.conf
  - sudo echo "wal_level = replica" >> $PGDATA/postgresql.conf
  - sudo echo "archive_mode = on" >> $PGDATA/postgresql.conf
  - sudo echo "archive_command = 'cp %p /home/travis/build/ossc-db/pg_rman/pg_data/archivelog/%f'" >> $PGDATA/postgresql.conf
  - pg_ctl -V
  - pg_ctl -D $PGDATA start

before_script:
  - cd /home/travis/build/ossc-db/pg_rman
  - git clone https://github.com/ossc-db/pg_rman.git pg_rman
  - cd pg_rman && git describe --alway
  - make
  - make install

env:
  matrix:
    - PGVERSION=11

language: cpp
compiler:
#  - clang
  - gcc

script: make installcheck

after_script:
  - cat /home/travis/build/ossc-db/pg_rman/pg_rman/regression.diffs

notifications:
  email:
    on_success: change
    on_failure: always
